version: '2'
services:

  crawler:
    image: inexus.ixxus.co.uk:28443/ixxus/hlv-webcrawler:development
    container_name: hlv-webcrawler
    ports:
      - "8090:8090"
    environment:
      SPRING_PROFILES_ACTIVE: "dev"
#    depends_on:
#      - configurator
#    volumes:
#      - ./data:/data
    build:
      context: ./hlv-crawler

